# Generated by Django 4.2 on 2025-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('whatsapp_phone_id', models.TextField()),
                ('whatsapp_token', models.TextField()),
                ('pinecone_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_phone_no', models.TextField()),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('who', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
            ],
            options={
                'db_table': 'conversations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
