# Generated by Django 4.2 on 2025-08-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
    ]
