# Generated by Django 4.2 on 2025-08-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_tag_alter_user_options_usertag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
